#!/bin/bash
output=$1
ref=$2
all_refs=("$ref"*)

exec java -mx2g \
	-Dfile.encoding=utf8 \
	-Djava.library.path=$HOME/src/incubator-joshua/lib \
	-cp $HOME/src/incubator-joshua/target/*-jar-with-dependencies.jar \
  org.apache.joshua.util.JoshuaEval \
  -cand "$output" \
  -format plain \
  -ref "$ref" \
  -rps "${#all_refs[@]}" \
  -m BLEU 4 closest \
  -v 0
